###
GET http://localhost:3000/api/groups

###
GET http://localhost:3000/api/groups/24

###

POST http://localhost:3000/api/groups
Content-Type: application/json

{
	"name": "string25",
	"password": "string25",
	"imageUrl": "string25",
	"isPublic": true,
	"introduction": "string25"
}

###
PUT http://localhost:3000/api/groups/24
Content-Type: application/json

{
	"name": "수정함24",
  "password": "string21",
	"imageUrl": "string25",
	"isPublic": true,
	"introduction": "ㅎㅇㅎㅇ수정햇다25"
}
###

DELETE http://localhost:3000/api/groups/25
Content-Type: application/json

{
  "password": "string25"
}


###
GET http://localhost:3000/api/groups/22/is-public

###
POST http://localhost:3000/api/groups/24/like

###
POST http://localhost:3000/api/groups/1/verify-password
Content-Type: application/json

{
  "password": "aaa"
}

###
GET http://localhost:3000/api/groups

###
GET http://localhost:3000/api/groups?sortBy=latest


###
GET http://localhost:3000/api/groups?&sortBy=mostPosted&isPublic=false&keyword=string

###
GET http://localhost:3000/api/groups?sortBy=mostPosted

###
GET http://localhost:3000/api/groups?sortBy=mostLiked

###
GET http://localhost:3000/api/groups?sortBy=mostBadge




###
GET http://localhost:3000/api/groups?